# Generated by Django 2.1.3 on 2018-11-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
