# Generated by Django 2.1.3 on 2018-11-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
